@startuml

interface ViewManager {
    public void addView(View view, ViewGroup.LayoutParams params);
    public void updateViewLayout(View view, ViewGroup.LayoutParams params);
    public void removeView(View view);
}

interface WindowManager {
}

class WindowManagerImpl {
}

class WindowManagerGlobal {
}

interface IBinder {
    {method} transact()
}

class Binder {
    {method} onTransact()
}

interface IWindowManager {
}

abstract class IWindowManager.Stub {  
}

class WindowManagerService {
}



ViewManager <|-- WindowManager 
WindowManager <|.. WindowManagerImpl

IBinder <|.. Binder
Binder <|-- IWindowManager.Stub
IWindowManager <|.. IWindowManager.Stub
IWindowManager.Stub <|-- WindowManagerService

@enduml